### ISSUE TITLE
Batch verify ReLU circuit has an error

### ISSUE THREAD

**Issue by amyzx** [scipr-lab/ripp#27]
Hi,
     I am a student learning zkSNARK. And I wrote a ReLU circuit in examples/relu_circuit_batch.rs following your examples/groth16_aggregation.rs and want to batch verify many ReLU circuits. 
     The insert code button does not work well, so I just paste the original codes. The codes in examples/relu_circuit_batch.rs are shown as follows. 
 

use ark_ip_proofs::applications::groth16_aggregation::{
    aggregate_proofs, setup_inner_product, verify_aggregate_proof,
};
use std::time::Instant;
use ark_bls12_381::{Bls12_381, Fr};
use ark_crypto_primitives::snark::*; 
use ark_groth16::Groth16;
use ark_r1cs_std::{fields::fp::FpVar, prelude::*};
use ark_relations::r1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError};
use ark_std::rand::{rngs::StdRng, SeedableRng};
use blake2::Blake2b;
use ark_r1cs_std::boolean::Boolean;
use ark_r1cs_std::eq::EqGadget;
pub type FqVar = FpVar<Fr>;

/* ReLU function:
    if y_in[i] < 0: 
        y_out[i] = 0 
        cmp_res[i] = false
    else: 
        y_out[i] = y_in[i] 
        cmp_res[i] = true
*/
#[derive(Debug, Clone)]
pub struct BatchReLUCircuit {
    pub y_in: Vec<u8>,
    pub y_out: Vec<u8>,
    pub y_zeropoint: u8,
    pub cmp_res: Vec<bool>,
}

impl ConstraintSynthesizer<Fr> for BatchReLUCircuit {
    fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
        let y_in_var = generate_fqvar(cs.clone(), self.y_in.clone());
        let y_out_var = generate_fqvar(cs.clone(), self.y_out.clone()); 
        let zero: Fr = self.y_zeropoint.into();
        let zero_var = FqVar::Constant(zero);  //zero point is constant wire in the circuit   
        for i in 0..self.y_in.len() {
            let cmp =
                Boolean::new_witness(cs.clone(),  || {
                    Ok(self.cmp_res[i])
                })
                .unwrap();
            y_out_var[i]
                .enforce_equal(&cmp.select(&y_in_var[i], &zero_var).unwrap())  // if cmp is true, then select the first item
                .unwrap(); 
        } 
        Ok(())
    }
}

// turn Vec<u8> to Vec<FqVar>
fn generate_fqvar(cs: ConstraintSystemRef<Fr>, input: Vec<u8>) -> Vec<FqVar> {
    let mut res: Vec<FqVar> = Vec::new();
    for i in 0..input.len() {
        let fq: Fr = input[i].into();
        let tmp = FpVar::<Fr>::new_witness(cs.clone(), || Ok(fq)).unwrap();
        res.push(tmp);
    }
    res
}

// implement relu by hand
fn relu_u8(input: &mut [u8], zero_point: u8) -> Vec<bool> {
    let mut cmp_res: Vec<bool> = Vec::new();
    for e in input {
        if *e < zero_point {
            *e = zero_point;
            cmp_res.push(false);
        } else {
            cmp_res.push(true);
        }
    }
    cmp_res
}
 
fn main() {
    const NUM_PROOFS_TO_AGGREGATE: usize = 4;
    const NUM_PUBLIC_INPUTS: usize = 5;
    let mut rng = StdRng::seed_from_u64(0u64);  
    let circuit = BatchReLUCircuit {
        y_in: vec![Default::default(); NUM_PUBLIC_INPUTS],
        y_out: vec![Default::default(); NUM_PUBLIC_INPUTS],
        y_zeropoint: Default::default(),
        cmp_res: vec![Default::default(); NUM_PUBLIC_INPUTS], 
    };
    let parameters = Groth16::<Bls12_381>::setup(circuit, &mut rng).unwrap();
    // Generate parameters for inner product aggregation
    let srs = setup_inner_product::<_, Blake2b, _>(&mut rng, NUM_PROOFS_TO_AGGREGATE).unwrap();
    // Generate proofs
    println!("Generating {} Groth16 proofs...", NUM_PROOFS_TO_AGGREGATE);
    let mut start = Instant::now();
    let mut proofs = Vec::new();
    let mut statements = Vec::new();
    for _ in 0..NUM_PROOFS_TO_AGGREGATE {  
        let statement = Vec::new();
        let y_in = vec![1u8, 2u8, 9u8, 100u8, 20u8];    
        let mut y_out = y_in.clone();
        let y_zeropoint = 3u8; 
        // get relu result and update y_out
        let cmp_res = relu_u8(&mut y_out, y_zeropoint); 
        let circuit = BatchReLUCircuit {
            y_in: y_in.clone(),
            y_out: y_out.clone(),
            y_zeropoint: y_zeropoint,
            cmp_res: cmp_res.clone(),
        }; 
        let proof = Groth16::<Bls12_381>::prove(&parameters.0, circuit.clone(), &mut rng).unwrap();
        proofs.push(proof);
        statements.push(statement); 
    }
    let generation_time = start.elapsed().as_millis();
    // Aggregate proofs using inner product proofs
    start = Instant::now();
    println!("Aggregating {} Groth16 proofs...", NUM_PROOFS_TO_AGGREGATE);
    let aggregate_proof = aggregate_proofs::<Bls12_381, Blake2b>(&srs, &proofs).unwrap();
    let prover_time = start.elapsed().as_millis();
    println!("Verifying aggregated proof...");
    start = Instant::now();
    let result = verify_aggregate_proof(
        &srs.get_verifier_key(),
        &parameters.0.vk,
        &statements,
        &aggregate_proof,
    )
    .unwrap();
    let verifier_time = start.elapsed().as_millis();
    assert!(result);
    println!("Proof generation time: {} ms", generation_time);
    println!("Proof aggregation time: {} ms", prover_time);
    println!("Proof verification time: {} ms", verifier_time);
}

I guess the _statements_ are used to collect all variables used in _new_input_ function. In my ReLU circuit, I only call _new_witness_ functions, so I set _statements_ as empty vector.
But I got the following error.  Could you help me to deal with this problem? I have no idea how to fix it. 

![image](https://user-images.githubusercontent.com/8285571/120606557-e5ca5580-c481-11eb-8600-d369561491f4.png)

Looking forward to your reply. Thanks!

**Comment by nirvantyagi** [comment]
Hello! Do the individual ReLU Groth16 proofs verify? (before aggregation)

I would add a ``Groth16::verify`` check after the ``Groth16::prove`` line in ``main`` to check this.

**Comment by amyzx** [comment]
> Hello! Do the individual ReLU Groth16 proofs verify? (before aggregation)
> 
> I would add a `Groth16::verify` check after the `Groth16::prove` line in `main` to check this.

Hi, I have fixed the problem. 
Because I wrote the following code `let zero_var = FqVar::Constant(zero);` in BatchReLUCircuit, when I setup the circuit the y_zeropoint is Default::default(), which is changed in the loop `for _ in 0..NUM_PROOFS_TO_AGGREGATE`. 
I used the same  y_zeropoint  in my code, and the program runs normally.
 
Thanks!
